# Generated by Django 5.0.1 on 2025-10-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RACKET', 'Tennis Racket'), ('M_APP', "Men's Apparel"), ('W_APP', "Women's Apparel"), ('J_APP', 'Junior Apparel'), ('M_SHOES', "Men's Shoes"), ('W_SHOES', "Women's Shoes"), ('J_SHOES', 'Junior Shoes'), ('BAGS', 'Tennis Bags'), ('STRINGS', 'Strings'), ('GRIPS', 'Grips and Accessories'), ('BALLS', 'Balls'), ('OTHER', 'Other')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='shop/products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='shop/products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='shop/products/')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('J', 'Junior'), ('U', 'Unisex')], default='U', max_length=1)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('material', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Apparel',
                'verbose_name_plural': 'Apparel',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('capacity_rackets', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Balls',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('balls_per_can', models.PositiveIntegerField(blank=True, null=True)),
                ('surface', models.CharField(choices=[('AC', 'All Court'), ('HC', 'Hard Court'), ('CL', 'Clay'), ('GR', 'Grass')], default='AC', max_length=2)),
            ],
            options={
                'verbose_name': 'Balls',
                'verbose_name_plural': 'Balls',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('head_size_sq_in', models.PositiveIntegerField(blank=True, null=True)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('balance_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('swingweight', models.PositiveIntegerField(blank=True, null=True)),
                ('string_pattern', models.CharField(blank=True, max_length=16, null=True)),
                ('is_strung', models.BooleanField(default=True)),
                ('grip_sizes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Racket',
                'verbose_name_plural': 'Rackets',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('J', 'Junior'), ('U', 'Unisex')], default='U', max_length=1)),
                ('surface', models.CharField(choices=[('AC', 'All Court'), ('HC', 'Hard Court'), ('CL', 'Clay'), ('GR', 'Grass')], default='AC', max_length=2)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoes',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('gauge_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('material', models.CharField(blank=True, max_length=80, null=True)),
                ('length_m', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'String',
                'verbose_name_plural': 'Strings',
            },
            bases=('shop.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['type', 'is_active'], name='shop_produc_type_5d3353_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock'], name='shop_produc_in_stoc_0a4395_idx'),
        ),
    ]
