# Generated by Django 5.0.1 on 2026-04-05 16:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoe_surface_default_clay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='surface',
            field=models.CharField(choices=[('AC', 'All Court'), ('HC', 'Hard Court'), ('CL', 'Clay'), ('GR', 'Grass'), ('PD', 'Padel')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='surface',
            field=models.CharField(choices=[('AC', 'All Court'), ('HC', 'Hard Court'), ('CL', 'Clay'), ('GR', 'Grass'), ('PD', 'Padel')], default='AC', max_length=2),
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total in GEL (₾); updated from line items on save.', max_digits=10)),
                ('customer_note', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True, help_text='Staff only, not shown to customer.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('variant_label', models.CharField(blank=True, help_text='Size, grip, colorway, etc.', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shoporder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
