# Generated by Django 5.0.1 on 2026-04-05 16:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_order_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
