# Generated by Django 5.0.1 on 2026-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_homepromostripsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(db_index=True, default=False, help_text='Show in Featured block on the shop home (up to 5, newest first).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('RACKET', 'Tennis Racket'), ('M_APP', "Men's Apparel"), ('W_APP', "Women's Apparel"), ('J_APP', 'Junior Apparel'), ('M_SHOES', "Men's Shoes"), ('W_SHOES', "Women's Shoes"), ('J_SHOES', 'Junior Shoes'), ('BAGS', 'Tennis Bags'), ('STRINGS', 'Strings'), ('GRIPS', 'Grips and Accessories'), ('BALLS', 'Balls'), ('ACCESSORIES', 'Accessories'), ('OTHER', 'Other')], db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'featured_product', '-created_at'], name='shop_produc_is_acti_560631_idx'),
        ),
    ]
