# Generated by Django 5.0.1 on 2026-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='width',
            field=models.CharField(blank=True, help_text='Width / last (e.g. D, 2E, Wide).', max_length=24, null=True),
        ),
    ]
