# Generated by Django 5.0.1 on 2026-04-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shoe_width_and_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeaturedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/featured_stories/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('link_label', models.CharField(blank=True, default='Shop now', max_length=120)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home featured story',
                'verbose_name_plural': 'Home featured story',
            },
        ),
        migrations.CreateModel(
            name='HomeHeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(default='The Line for Your Growth', help_text='Use a line break for a second line, e.g. before “Your Growth”.')),
                ('subtext', models.TextField(blank=True, default='Curated tennis equipment from top brands. Free delivery in Tbilisi. Pre-order from US & EU with official customs clearance.')),
                ('cta_label', models.CharField(default='Shop Preorder', max_length=120)),
                ('cta_url', models.CharField(default='/shop/preorder', max_length=500)),
                ('secondary_link_label', models.CharField(blank=True, max_length=120)),
                ('secondary_link_url', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home hero text & CTAs',
                'verbose_name_plural': 'Home hero text & CTAs',
            },
        ),
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/hero_slides/')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('image_link_url', models.CharField(blank=True, max_length=500)),
                ('internal_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home hero slide',
                'verbose_name_plural': 'Home hero slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
