# Generated by Django 5.0.1 on 2026-04-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_home_hero_featured_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('lead', models.TextField(blank=True, help_text='Short intro under the title (plain text).')),
                ('body', models.TextField(blank=True, help_text='Article body (plain text; line breaks preserved).')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='shop/blog/')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='homefeaturedstory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Home featured story', 'verbose_name_plural': 'Home featured stories'},
        ),
        migrations.AddField(
            model_name='homefeaturedstory',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='homefeaturedstory',
            name='link_label',
            field=models.CharField(blank=True, default='Read more', max_length=120),
        ),
        migrations.AlterField(
            model_name='homefeaturedstory',
            name='link_url',
            field=models.CharField(blank=True, help_text='Used when no blog post is selected (e.g. /shop/blog/your-slug/).', max_length=500),
        ),
        migrations.AddField(
            model_name='homefeaturedstory',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_featured_cards', to='shop.blogpost'),
        ),
    ]
