# Generated by Django 5.0.1 on 2026-04-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_blog_featured_stories_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeBanner',
        ),
    ]
