# Generated by Django 5.0.1 on 2026-04-08 08:09

from django.db import migrations, models


def _copy_featured_from_home_cards(apps, schema_editor):
    HomeFeaturedStory = apps.get_model('shop', 'HomeFeaturedStory')
    BlogPost = apps.get_model('shop', 'BlogPost')
    for fs in HomeFeaturedStory.objects.filter(blog_post_id__isnull=False).order_by('sort_order', 'id'):
        bp = BlogPost.objects.filter(pk=fs.blog_post_id).first()
        if not bp:
            continue
        BlogPost.objects.filter(pk=bp.pk).update(
            is_featured_on_home=bool(fs.is_active),
            featured_sort_order=fs.sort_order,
            featured_cta_label=(fs.link_label or '')[:120],
        )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Portrait image for the home “Featured stories” carousel (3:4 works best). Falls back to hero if empty.', null=True, upload_to='shop/blog/cards/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_cta_label',
            field=models.CharField(blank=True, default='', help_text='Button text on the home card (default: Read more).', max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first in the home carousel.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured_on_home',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this post in the Featured stories carousel on the shop home page.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Wide image for the article page header (landscape recommended).', null=True, upload_to='shop/blog/'),
        ),
        migrations.RunPython(_copy_featured_from_home_cards, _noop_reverse),
        migrations.DeleteModel(
            name='HomeFeaturedStory',
        ),
    ]
