# Generated by Django 5.0.1 on 2026-04-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_blog_featured_unify'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='article_image_1',
            field=models.ImageField(blank=True, help_text='Optional extra image for the body (1/3).', null=True, upload_to='shop/blog/inline/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='article_image_2',
            field=models.ImageField(blank=True, help_text='Optional extra image for the body (2/3).', null=True, upload_to='shop/blog/inline/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='article_image_3',
            field=models.ImageField(blank=True, help_text='Optional extra image for the body (3/3).', null=True, upload_to='shop/blog/inline/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_end_button_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_end_button_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_end_text',
            field=models.CharField(blank=True, help_text='Ending CTA heading text.', max_length=240),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_mid_button_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_mid_button_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_mid_text',
            field=models.CharField(blank=True, help_text='Middle CTA heading text.', max_length=240),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_product_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_featured_slot_1', to='shop.product'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_featured_slot_2', to='shop.product'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_featured_slot_3', to='shop.product'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_product_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_featured_slot_4', to='shop.product'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_product_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_featured_slot_5', to='shop.product'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quote_author',
            field=models.CharField(blank=True, help_text='Optional quote author/signature.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quote_text',
            field=models.TextField(blank=True, help_text='Highlighted quote block shown mid-article.'),
        ),
    ]
