# Generated by Django 5.0.1 on 2026-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_blog_post_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_block_1',
            field=models.TextField(blank=True, help_text='Article text block 1/5.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_block_2',
            field=models.TextField(blank=True, help_text='Article text block 2/5.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_block_3',
            field=models.TextField(blank=True, help_text='Article text block 3/5.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_block_4',
            field=models.TextField(blank=True, help_text='Article text block 4/5.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_block_5',
            field=models.TextField(blank=True, help_text='Article text block 5/5.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, help_text='Legacy aggregated body (auto-built from text blocks).'),
        ),
    ]
