# Generated by Django 5.0.1 on 2026-04-10 09:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_blogpost_body_block_5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceYearSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, unique=True)),
                ('last_seq', models.PositiveIntegerField(default=38)),
            ],
            options={
                'verbose_name': 'Sales invoice sequence (year)',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('newsletter_opt_in', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('order_date', models.DateField(db_index=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery / extra charge, VAT-inclusive (₾).', max_digits=10)),
                ('fiscal_receipt', models.CharField(blank=True, max_length=64)),
                ('payment_method', models.CharField(blank=True, max_length=200)),
                ('services', models.JSONField(blank=True, default=list, help_text='List of {"name": str, "gross": str|number} — VAT-inclusive amounts.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='shop.customer')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_gross', models.DecimalField(decimal_places=2, help_text='Unit price including VAT (₾).', max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='shop.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='shop_custom_phone_70f608_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='shop_custom_email_5770bc_idx'),
        ),
    ]
