# Generated by Django 5.0.1 on 2026-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_retail_customers_and_sales_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_local',
            field=models.CharField(blank=True, help_text='Georgian / local script first name (optional).', max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='surname_local',
            field=models.CharField(blank=True, help_text='Georgian / local script last name (optional).', max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='tg_account',
            field=models.CharField(blank=True, help_text='Telegram username or handle (optional).', max_length=64),
        ),
    ]
