# Generated by Django 5.0.1 on 2026-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_customer_local_names_and_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending payment'), ('PAID', 'Paid'), ('AWAITING_PICKUP', 'Awaiting pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PAID', max_length=24),
        ),
    ]
