# Generated by Django 5.0.1 on 2026-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_salesinvoice_sequence_2026_next_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='gauges',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
