# Generated by Django 5.0.1 on 2026-04-14

from django.db import migrations, models


def map_legacy_statuses(apps, schema_editor):
    SalesOrder = apps.get_model('shop', 'SalesOrder')
    mapping = {
        'PENDING': 'SUBMITTED',
        'PAID': 'SUBMITTED',
        'AWAITING_PICKUP': 'CONFIRMED',
        'COMPLETED': 'SHIPPED',
    }
    for old, new in mapping.items():
        SalesOrder.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_user_cart_models'),
    ]

    operations = [
        migrations.RunPython(map_legacy_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('SUBMITTED', 'Submitted'),
                    ('CONFIRMED', 'Confirmed'),
                    ('SHIPPED', 'Shipped'),
                    ('CANCELLED', 'Cancelled'),
                    ('REFUNDED', 'Refunded'),
                ],
                db_index=True,
                default='SUBMITTED',
                max_length=24,
            ),
        ),
    ]
