# Generated by Django 5.0.1 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_salesorder_status_submitted_confirmed_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('SUBMITTED', 'Submitted'),
                    ('AWAITING_PAYMENT', 'Awaiting payment'),
                    ('CONFIRMED', 'Confirmed'),
                    ('SHIPPED', 'Shipped'),
                    ('COMPLETED', 'Completed'),
                    ('CANCELLED', 'Cancelled'),
                    ('REFUNDED', 'Refunded'),
                ],
                db_index=True,
                default='SUBMITTED',
                max_length=24,
            ),
        ),
    ]
