# Generated by Django 5.0.1 on 2026-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_salesorder_status_add_awaiting_payment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('RACKET', 'Tennis Racket'), ('M_APP', "Men's Apparel"), ('W_APP', "Women's Apparel"), ('J_APP', 'Junior Apparel'), ('M_SHOES', "Men's Shoes"), ('W_SHOES', "Women's Shoes"), ('J_SHOES', 'Junior Shoes'), ('BAGS', 'Tennis Bags'), ('STRINGS', 'Strings'), ('GRIPS', 'Grips'), ('DAMPENERS', 'Dampeners'), ('BALLS', 'Balls'), ('ACCESSORIES', 'Accessories'), ('OTHER', 'Other')], db_index=True, max_length=16),
        ),
    ]
