# Generated by Django 5.0.1 on 2026-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended size: 1600x420 px or similar wide landscape ratio.', upload_to='shop/home_promo_banners/')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('image_link_url', models.CharField(blank=True, max_length=500)),
                ('internal_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home promo banner',
                'verbose_name_plural': 'Home promo banners',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Recommended size: 1600x560 px or similar wide banner ratio.', null=True, upload_to='shop/collections/')),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product collection',
                'verbose_name_plural': 'Product collections',
                'ordering': ['title', 'id'],
            },
        ),
    ]
