# Generated by Django 5.0.1 on 2026-04-19 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_homepromobanner_productcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepromobanner',
            name='image',
            field=models.FileField(help_text='Raster (PNG/JPEG/WebP) or SVG. Recommended raster size: 1600x420 px (wide landscape). SVG keeps text sharp at any width.', upload_to='shop/home_promo_banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'webp', 'svg'))]),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='banner_image',
            field=models.FileField(blank=True, help_text='Raster (PNG/JPEG/WebP) or SVG. Recommended raster size: 1600x560 px (wide banner). SVG keeps text sharp at any width.', null=True, upload_to='shop/collections/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'webp', 'svg'))]),
        ),
    ]
