# Generated by Django 5.0.1 on 2026-04-20 06:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_collection_promo_banner_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('image', models.FileField(blank=True, help_text='Optional square image for this group. Raster recommendation: 1200x1200 px. SVG is allowed.', null=True, upload_to='shop/collections/groups/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'webp', 'svg'))])),
                ('title', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='shop.productcollection')),
                ('products', models.ManyToManyField(blank=True, related_name='collection_groups', to='shop.product')),
            ],
            options={
                'verbose_name': 'Collection group',
                'verbose_name_plural': 'Collection groups',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
