# Generated by Django 5.0.1 on 2026-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_sync_django_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='article_image_1',
            field=models.FileField(blank=True, help_text='Optional inline figure (1/3). Raster (JPEG/PNG/WebP) is auto-optimized; SVG is allowed.', null=True, upload_to='shop/blog/inline/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='article_image_2',
            field=models.FileField(blank=True, help_text='Optional inline figure (2/3). Raster is auto-optimized; SVG is allowed.', null=True, upload_to='shop/blog/inline/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='article_image_3',
            field=models.FileField(blank=True, help_text='Optional inline figure (3/3). Raster is auto-optimized; SVG is allowed.', null=True, upload_to='shop/blog/inline/'),
        ),
    ]
