# Generated by Django 5.0.1 on 2026-07-27 09:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_sales_order_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='custom_label',
            field=models.CharField(blank=True, default='', help_text='Free-text item name for non-stock lines (when product is empty).', max_length=200),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='amount_in_payment_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Order gross in payment_currency (gross_total ÷ exchange_rate).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='₾ per 1 unit of payment currency; foreign amount = gross_total ÷ rate (1 for GEL).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Empty for non-stock (legacy / free-text) lines.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='shop.product'),
        ),
    ]
