# Generated by Django 5.0.1 on 2026-07-27 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_salesorderline_custom_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='landed_cost_gel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Staff-only: weighted-average landed cost per unit (₾). Updated via stock receipts; never shown to shoppers.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='landed_cost_gel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Staff-only: per-unit landed cost (₾), snapshotted when the order is saved. Never shown on invoices or to customers.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Units in this batch.')),
                ('unit_landed_cost_gel', models.DecimalField(decimal_places=2, help_text='Landed cost per unit for this batch (₾).', max_digits=10)),
                ('on_hand_before', models.PositiveIntegerField(help_text='Units on hand before this batch (averaging basis).')),
                ('landed_cost_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('landed_cost_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
