# Generated by Django 5.0.1 on 2026-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_product_landed_cost_gel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='stock_added',
            field=models.BooleanField(default=False, help_text='Whether this receipt also increased the STOCK listing quantity.'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='variant_label',
            field=models.CharField(blank=True, default='', help_text='Grip / shoe or apparel size / string gauge the batch was added to.', max_length=48),
        ),
    ]
