# Generated by Django 5.0.1 on 2026-07-29 09:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_stockreceipt_stock_added_stockreceipt_variant_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_cost_gel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Staff-only: what we pay the delivery contractor (₾). Counts toward order COGS with product landed costs. Never shown to customers.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='List of {"name": str, "gross": str|number, "cost": str|number} — VAT-inclusive customer amounts; cost is staff-only contractor pay (₾).'),
        ),
    ]
