# Generated by Django 5.0.1 on 2026-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_salesorder_delivery_cost_and_service_cost_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('units', models.PositiveIntegerField(default=0)),
                ('shelf_value_gel', models.DecimalField(decimal_places=2, help_text='Σ qty × min(actual, initial) shelf price (₾).', max_digits=14)),
                ('landed_value_gel', models.DecimalField(decimal_places=2, help_text='Σ qty × Product.landed_cost_gel for units with a known cost (₾).', max_digits=14)),
                ('source', models.CharField(choices=[('measured', 'Measured'), ('estimated', 'Estimated')], db_index=True, default='measured', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
