# Generated by Django 5.0.1 on 2026-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_stock_value_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='sale_channel',
            field=models.CharField(choices=[('STOCK', 'In stock'), ('PREORDER', 'Preorder')], db_index=True, default='STOCK', help_text='Staff analytics: sold from shelf stock or as a preorder. Defaults to In stock; change retrospectively as needed.', max_length=16),
        ),
    ]
