# Generated by Django 5.0.1 on 2026-07-30 11:51

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_product_type(apps, schema_editor):
    """Copy category from linked catalog product onto existing stock lines."""
    SalesOrderLine = apps.get_model('shop', 'SalesOrderLine')
    Product = apps.get_model('shop', 'Product')
    SalesOrderLine.objects.filter(product_id__isnull=False).update(
        product_type=Subquery(
            Product.objects.filter(pk=OuterRef('product_id')).values('type')[:1]
        )
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_salesorderline_sale_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='product_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('RACKET', 'Tennis Racket'),
                    ('M_APP', "Men's Apparel"),
                    ('W_APP', "Women's Apparel"),
                    ('J_APP', 'Junior Apparel'),
                    ('M_SHOES', "Men's Shoes"),
                    ('W_SHOES', "Women's Shoes"),
                    ('J_SHOES', 'Junior Shoes'),
                    ('BAGS', 'Tennis Bags'),
                    ('STRINGS', 'Strings'),
                    ('GRIPS', 'Grips'),
                    ('DAMPENERS', 'Dampeners'),
                    ('BALLS', 'Balls'),
                    ('ACCESSORIES', 'Accessories'),
                    ('OTHER', 'Other'),
                ],
                db_index=True,
                default='',
                help_text=(
                    'Product category for analytics. Auto-set from the catalog product; '
                    'required on legacy free-text lines.'
                ),
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_product_type, noop_reverse),
    ]
