# Generated by Django 5.0.1 on 2026-09-29 08:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_salesorderpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_on', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('personal', 'Personal'), ('advertising', 'Advertising'), ('demo', 'Demo'), ('barter', 'Barter'), ('blogger', 'Blogger'), ('other', 'Other')], db_index=True, max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_write_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-written_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockWriteOffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_label', models.CharField(blank=True, default='', max_length=48)),
                ('quantity', models.PositiveIntegerField()),
                ('landed_cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of the written-off units’ batch costs (₾). Not revenue.', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_write_off_lines', to='shop.product')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.stockwriteoff')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_label', models.CharField(blank=True, default='', max_length=48)),
                ('unit_landed_cost_gel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, help_text='Empty until staff dates a past batch, or a new receipt stamps it.', null=True)),
                ('status', models.CharField(choices=[('on_hand', 'On hand'), ('sold', 'Sold'), ('written_off', 'Written off')], db_index=True, default='on_hand', max_length=16)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('written_off_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='shop.product')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='shop.stockreceipt')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_units', to='shop.salesorderline')),
                ('write_off_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='shop.stockwriteoffline')),
            ],
            options={
                'ordering': ['received_at', 'id'],
                'indexes': [models.Index(fields=['product', 'status', 'received_at'], name='shop_stocku_product_257ef2_idx'), models.Index(fields=['status', 'variant_label'], name='shop_stocku_status_056301_idx')],
            },
        ),
    ]
