# Generated by Django 5.0.1 on 2026-10-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_stock_unit_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_label', models.CharField(blank=True, default='', max_length=48)),
                ('barcode', models.CharField(db_index=True, max_length=64, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='shop.product')),
            ],
            options={
                'ordering': ['product_id', 'variant_label', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('product', 'variant_label'), name='shop_product_barcode_unique_variant'),
        ),
    ]
