# Generated by Django 5.0.1 on 2024-05-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_city',
            field=models.CharField(choices=[('MTA', 'Malta All'), ('TBI', 'Tbilisi, GE'), ('BAT', 'Batumi, GE'), ('MSC', 'Moscow, RU'), ('SPB', 'St. Petersburg, RU')], default='TBI', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_geo',
            field=models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('ME', 'Montenegro'), ('GE', 'Georgia')], default='GE', max_length=2),
        ),
    ]
