# Generated by Django 5.0.1 on 2025-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_test_user',
            field=models.BooleanField(default=False),
        ),
    ]
