# Generated by Django 5.0.1 on 2025-03-11 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_telegramverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverification',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramverification',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegramverification',
            name='verification_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
