# Generated by Django 5.0.1 on 2025-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_telegramverification_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_telegram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
