# Generated by Django 5.0.1 on 2025-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_alter_customuser_managers_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False, help_text='Indicates whether the user agreed to receive news and offers.', verbose_name='agreed to receive newsletter'),
        ),
    ]
