# Generated by Django 5.0.1 on 2025-05-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_customuser_newsletter_opt_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
