# Generated by Django 5.0.1 on 2024-12-26 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_stage', models.SmallIntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('court', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('FI', 'Finished')], default='PD', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('X', 'Mixed'), ('F', 'Women')], max_length=1, null=True)),
                ('pair_since', models.DateField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PairMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(null=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('set1_score', models.PositiveSmallIntegerField(default=0)),
                ('set1_tie_score', models.PositiveSmallIntegerField(null=True)),
                ('set1_won', models.BooleanField(null=True)),
                ('set2_score', models.PositiveSmallIntegerField(null=True)),
                ('set2_tie_score', models.PositiveSmallIntegerField(null=True)),
                ('set2_won', models.BooleanField(null=True)),
                ('set3_score', models.PositiveSmallIntegerField(null=True)),
                ('set3_tie_score', models.PositiveSmallIntegerField(null=True)),
                ('set3_won', models.BooleanField(null=True)),
                ('_set3_is_tiebreak', models.BooleanField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_matches', to='rivals.match')),
                ('opponent', models.ForeignKey(on_delete=models.SET('0'), related_name='the_opponent_pair', to='rivals.pair')),
                ('pair', models.ForeignKey(on_delete=models.SET('0'), related_name='the_pair', to='rivals.pair')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='pairs',
            field=models.ManyToManyField(related_name='match_as_pair', through='rivals.PairMatch', to='rivals.pair'),
        ),
        migrations.CreateModel(
            name='PairSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2024)),
                ('pts', models.PositiveIntegerField(default=0)),
                ('final_rating_pts', models.PositiveIntegerField(default=1000)),
                ('start_rating_pts', models.PositiveIntegerField(default=1000)),
                ('max_rating_pts', models.PositiveIntegerField(default=1000)),
                ('min_rating_pts', models.PositiveIntegerField(default=1000)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.pair')),
            ],
        ),
        migrations.CreateModel(
            name='PairTotalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rating_pts', models.PositiveIntegerField(default=1000)),
                ('max_rating_pts', models.PositiveIntegerField(default=1000)),
                ('min_rating_pts', models.PositiveIntegerField(default=1000)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.pair')),
            ],
        ),
        migrations.CreateModel(
            name='PairTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(null=True)),
                ('flow', models.CharField(default='', max_length=5)),
                ('pair', models.ForeignKey(on_delete=models.SET('0'), to='rivals.pair')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', "Men's Tournaments"), ('F', "Women's Tournaments")], max_length=1, null=True)),
                ('geo', models.CharField(default='GE', max_length=2)),
                ('city', models.CharField(default='TBI', max_length=3)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('tennis_exp_year', models.PositiveIntegerField(null=True)),
                ('availability', models.TextField(null=True)),
                ('player_since', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(null=True, upload_to='avatars/')),
                ('level_current', models.FloatField(null=True)),
                ('level_log', models.JSONField(default=dict)),
                ('rating_pts', models.PositiveIntegerField(default=0)),
                ('attributes', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=models.SET('0'), related_name='pair_p1_set', to='rivals.player'),
        ),
        migrations.AddField(
            model_name='pair',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=models.SET('0'), related_name='pair_p2_set', to='rivals.player'),
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(null=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('set1_score', models.PositiveSmallIntegerField(default=0)),
                ('set1_tie_score', models.PositiveSmallIntegerField(null=True)),
                ('set1_won', models.BooleanField(null=True)),
                ('set2_score', models.PositiveSmallIntegerField(null=True)),
                ('set2_tie_score', models.PositiveSmallIntegerField(null=True)),
                ('set2_won', models.BooleanField(null=True)),
                ('set3_score', models.PositiveSmallIntegerField(null=True)),
                ('set3_tie_score', models.PositiveSmallIntegerField(null=True)),
                ('set3_won', models.BooleanField(null=True)),
                ('set3_is_tiebreak', models.BooleanField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_matches', to='rivals.match')),
                ('opponent', models.ForeignKey(on_delete=models.SET('0'), related_name='the_opponent', to='rivals.player')),
                ('player', models.ForeignKey(on_delete=models.SET('0'), related_name='the_player', to='rivals.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='match_as_player', through='rivals.PlayerMatch', to='rivals.player'),
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2024)),
                ('pts', models.PositiveIntegerField(default=0)),
                ('final_rating_pts', models.PositiveIntegerField(default=1000)),
                ('start_rating_pts', models.PositiveIntegerField(default=1000)),
                ('max_rating_pts', models.PositiveIntegerField(default=1000)),
                ('min_rating_pts', models.PositiveIntegerField(default=1000)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTotalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rating_pts', models.PositiveIntegerField(default=1000)),
                ('max_rating_pts', models.PositiveIntegerField(default=1000)),
                ('min_rating_pts', models.PositiveIntegerField(default=1000)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(null=True)),
                ('flow', models.CharField(default='', max_length=8)),
                ('player', models.ForeignKey(on_delete=models.SET('0'), to='rivals.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(choices=[('RM', 'Ranked Match'), ('GM', 'Group Match'), ('OS', 'Olympic System')], default='RM', max_length=2)),
                ('category', models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C3', 'Masters'), ('PR', 'Profi')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('X', 'Mixed'), ('F', 'Women')], max_length=1)),
                ('format', models.CharField(choices=[('S', 'Singles'), ('D', 'Doubles')], max_length=2)),
                ('geo', models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('GE', 'Georgia'), ('RU', 'Russia')], default='GE', max_length=2)),
                ('city', models.CharField(choices=[('MTA', 'Malta All, MT'), ('TBI', 'Tbilisi, GE'), ('BAT', 'Batumi, GE'), ('MSC', 'Moscow, RU'), ('SPB', 'St. Petersburg, RU'), ('MIL', 'Milano, IT'), ('ROM', 'Roma, IT'), ('BEL', 'Belgrad, RS')], default='TBI', max_length=3)),
                ('status', models.CharField(choices=[('CI', 'Check-in Open'), ('AC', 'In Action'), ('FI', 'Finished')], default='CI', max_length=2)),
                ('start_date', models.DateField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('current_stage', models.SmallIntegerField(default=0)),
                ('current_stage_start_date', models.DateField(null=True)),
                ('current_stage_end_date', models.DateField(null=True)),
                ('players_num', models.PositiveSmallIntegerField()),
                ('players_enrolled', models.PositiveSmallIntegerField(default=0)),
                ('pairs', models.ManyToManyField(through='rivals.PairTournament', to='rivals.pair')),
                ('players', models.ManyToManyField(through='rivals.PlayerTournament', to='rivals.player')),
            ],
        ),
        migrations.AddField(
            model_name='playertournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.tournament'),
        ),
        migrations.AddField(
            model_name='pairtournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.tournament'),
        ),
    ]
