# Generated by Django 5.0.1 on 2024-12-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
