# Generated by Django 5.0.1 on 2024-05-20 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='_date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='_city',
            field=models.CharField(default='TBI', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='_geo',
            field=models.CharField(default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='_city',
            field=models.CharField(choices=[('MTA', 'Malta All'), ('TBI', 'Tbilisi'), ('BAT', 'Batumi'), ('MSC', 'Moscow'), ('SPB', 'St. Petersburg')], default='TBI', max_length=3),
        ),
    ]
