# Generated by Django 5.0.1 on 2025-01-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0002_player_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairseasonstats',
            name='season',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='season',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
