# Generated by Django 5.0.1 on 2024-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0002_tournament__date_created_alter_player__city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='_status',
            field=models.CharField(choices=[('CI', 'Check-in Open'), ('AC', 'In Action'), ('FI', 'Finished')], default='CI', max_length=2),
        ),
    ]
