# Generated by Django 5.0.1 on 2025-01-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0003_alter_pairseasonstats_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.CharField(choices=[('MTA', 'Malta All, MT'), ('TBI', 'Tbilisi, GE'), ('BAT', 'Batumi, GE'), ('MSC', 'Moscow, RU'), ('SPB', 'St. Petersburg, RU'), ('MIL', 'Milano, IT'), ('ROM', 'Roma, IT'), ('BEL', 'Belgrade, RS')], default='TBI', max_length=3),
        ),
    ]
