# Generated by Django 5.0.1 on 2024-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0003_alter_tournament__status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='_gender',
            field=models.CharField(choices=[('M', 'Men'), ('X', 'Mixed'), ('F', 'Women')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='_category',
            field=models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C3', 'Masters'), ('PR', 'Profi')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='_gender',
            field=models.CharField(choices=[('M', 'Men'), ('X', 'Mixed'), ('F', 'Women')], max_length=1),
        ),
    ]
