# Generated by Django 5.0.1 on 2025-01-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0004_alter_tournament_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='level_current',
            new_name='NTRP_current',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='level_log',
            new_name='NTRP_log',
        ),
    ]
