# Generated by Django 5.0.1 on 2024-05-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0004_alter_pair__gender_alter_tournament__category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='_city',
            field=models.CharField(choices=[('MTA', 'Malta All'), ('TBI', 'Tbilisi, GE'), ('BAT', 'Batumi, GE'), ('MSC', 'Moscow, RU'), ('SPB', 'St. Petersburg, RU')], default='TBI', max_length=3),
        ),
    ]
