# Generated by Django 5.0.1 on 2024-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0005_alter_tournament__city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='_city',
            field=models.CharField(choices=[('MTA', 'Malta All, MT'), ('TBI', 'Tbilisi, GE'), ('BAT', 'Batumi, GE'), ('MSC', 'Moscow, RU'), ('SPB', 'St. Petersburg, RU'), ('MIL', 'Milano, IT'), ('ROM', 'Roma, IT'), ('BEL', 'Belgrad, RS')], default='TBI', max_length=3),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='_geo',
            field=models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('GE', 'Georgia'), ('RU', 'Russia')], default='GE', max_length=2),
        ),
    ]
