# Generated by Django 5.0.1 on 2025-01-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0005_rename_level_current_player_ntrp_current_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairseasonstats',
            old_name='pts',
            new_name='season_pts',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='max_rating_pts',
            new_name='max_season_NTRP',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='min_rating_pts',
            new_name='min_season_NTRP',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='final_rating_pts',
            new_name='season_final_NTRP',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='pts',
            new_name='season_pts',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='start_rating_pts',
            new_name='season_start_NTRP',
        ),
        migrations.RenameField(
            model_name='playertotalstats',
            old_name='current_rating_pts',
            new_name='current_NTRP',
        ),
        migrations.RenameField(
            model_name='playertotalstats',
            old_name='max_rating_pts',
            new_name='max_NTRP',
        ),
        migrations.RenameField(
            model_name='playertotalstats',
            old_name='min_rating_pts',
            new_name='min_NTRP',
        ),
        migrations.RemoveField(
            model_name='pairseasonstats',
            name='final_rating_pts',
        ),
        migrations.RemoveField(
            model_name='pairseasonstats',
            name='max_rating_pts',
        ),
        migrations.RemoveField(
            model_name='pairseasonstats',
            name='min_rating_pts',
        ),
        migrations.RemoveField(
            model_name='pairseasonstats',
            name='start_rating_pts',
        ),
        migrations.RemoveField(
            model_name='pairtotalstats',
            name='current_rating_pts',
        ),
        migrations.RemoveField(
            model_name='pairtotalstats',
            name='max_rating_pts',
        ),
        migrations.RemoveField(
            model_name='pairtotalstats',
            name='min_rating_pts',
        ),
        migrations.AddField(
            model_name='pairmatch',
            name='season_pts_gained',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='NTRP_gained',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='season_pts_gained',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PairRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C3', 'Masters'), ('PR', 'Profi')], max_length=2)),
                ('geo', models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('GE', 'Georgia'), ('RU', 'Russia')], default='GE', max_length=2)),
                ('season', models.PositiveIntegerField(default=2025)),
                ('week', models.PositiveIntegerField(default=3)),
                ('ranking_absolute', models.PositiveIntegerField(default=0)),
                ('ranking_category', models.PositiveIntegerField(default=0)),
                ('ranking_pts', models.PositiveIntegerField(default=0)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.pair')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C3', 'Masters'), ('PR', 'Profi')], max_length=2)),
                ('geo', models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('GE', 'Georgia'), ('RU', 'Russia')], default='GE', max_length=2)),
                ('season', models.PositiveIntegerField(default=2025)),
                ('week', models.PositiveIntegerField(default=3)),
                ('ranking_absolute', models.PositiveIntegerField(default=0)),
                ('ranking_category', models.PositiveIntegerField(default=0)),
                ('ranking_pts', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.player')),
            ],
        ),
    ]
