# Generated by Django 5.0.1 on 2025-01-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0006_rename_pts_pairseasonstats_season_pts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='NTRP_log',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attributes',
        ),
        migrations.AddField(
            model_name='player',
            name='is_fake',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pairranking',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_ranking', to='rivals.pair'),
        ),
        migrations.AlterField(
            model_name='pairseasonstats',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='rivals.pair'),
        ),
        migrations.AlterField(
            model_name='pairtotalstats',
            name='pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_stats', to='rivals.pair'),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_ranking', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playertotalstats',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_stats', to='rivals.player'),
        ),
        migrations.CreateModel(
            name='PlayerAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forehand', models.FloatField(default=0)),
                ('backhand', models.FloatField(default=0)),
                ('rallies', models.FloatField(default=0)),
                ('attack', models.FloatField(default=0)),
                ('serve', models.FloatField(default=0)),
                ('serve_return', models.FloatField(default=0)),
                ('volleys', models.FloatField(default=0)),
                ('responses_amount', models.PositiveIntegerField(default=0)),
                ('summary', models.FloatField(default=0)),
                ('oppo_score', models.FloatField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='rivals.player')),
            ],
        ),
    ]
