# Generated by Django 5.0.1 on 2025-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0007_remove_player_ntrp_log_remove_player_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C3', 'Masters'), ('PR', 'Profi')], default='C0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pairtournament',
            name='flow',
            field=models.CharField(default='', max_length=8),
        ),
    ]
