# Generated by Django 5.0.1 on 2025-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0008_player_category_alter_pairtournament_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairseasonstats',
            name='matches_rted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertotalstats',
            name='matches_rted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
