# Generated by Django 5.0.1 on 2025-01-16 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0009_pairseasonstats_matches_rted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('S', 'Singles'), ('D', 'Doubles')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='court',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pairs',
            field=models.ManyToManyField(related_name='matches_as_pair', through='rivals.PairMatch', to='rivals.pair'),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches_as_player', through='rivals.PlayerMatch', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rivals.tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament_stage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_sent', to='rivals.player')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to='rivals.player')),
            ],
        ),
    ]
