# Generated by Django 5.0.1 on 2025-01-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0010_alter_player_options_match_match_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='opponent',
            field=models.ForeignKey(on_delete=models.SET('0'), related_name='opponent_matches', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='player',
            field=models.ForeignKey(on_delete=models.SET('0'), related_name='player_matches', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playertournament',
            name='player',
            field=models.ForeignKey(on_delete=models.SET('0'), related_name='player_tournaments', to='rivals.player'),
        ),
    ]
