# Generated by Django 5.0.1 on 2025-01-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0011_alter_playermatch_opponent_alter_playermatch_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerattributes',
            name='oppo_score',
        ),
        migrations.AlterField(
            model_name='player',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlayerFeedbackAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forehand', models.FloatField(default=0)),
                ('backhand', models.FloatField(default=0)),
                ('rallies', models.FloatField(default=0)),
                ('attack', models.FloatField(default=0)),
                ('serve', models.FloatField(default=0)),
                ('serve_return', models.FloatField(default=0)),
                ('volleys', models.FloatField(default=0)),
                ('summary', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_attributes_from', to='rivals.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_attributes', to='rivals.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
