# Generated by Django 5.0.1 on 2025-01-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0012_remove_playerattributes_oppo_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='NTRP_current',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rating_pts',
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(null=True, upload_to='tournament_images/'),
        ),
    ]
