# Generated by Django 5.0.1 on 2025-01-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0013_remove_player_ntrp_current_remove_player_rating_pts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerranking',
            name='player',
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='geo',
            field=models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('GE', 'Georgia'), ('RU', 'Russia')], default='GE', max_length=2),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='ranking_absolute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='ranking_category',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PairRanking',
        ),
        migrations.DeleteModel(
            name='PlayerRanking',
        ),
    ]
