# Generated by Django 5.0.1 on 2025-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0014_remove_playerranking_player_playerseasonstats_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='category',
            field=models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C3', 'Masters'), ('PR', 'Profi')], default='C0', max_length=2),
        ),
    ]
