# Generated by Django 5.0.1 on 2025-01-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0015_playerseasonstats_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseasonstats',
            name='category',
        ),
    ]
