# Generated by Django 5.0.1 on 2025-01-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0016_remove_playerseasonstats_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='matches_rted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='PlayerCurrentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_rted', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('matches_played_this_season', models.PositiveIntegerField(default=0)),
                ('matches_won_this_season', models.PositiveIntegerField(default=0)),
                ('matches_rted_this_season', models.PositiveIntegerField(default=0)),
                ('matches_lost_this_season', models.PositiveIntegerField(default=0)),
                ('season_pts', models.PositiveIntegerField(default=0)),
                ('current_NTRP', models.PositiveIntegerField(default=1000)),
                ('season_start_NTRP', models.PositiveIntegerField(default=1000)),
                ('max_NTRP', models.PositiveIntegerField(default=1000)),
                ('min_NTRP', models.PositiveIntegerField(default=1000)),
                ('max_NTRP_this_season', models.PositiveIntegerField(default=1000)),
                ('min_NTRP_this_season', models.PositiveIntegerField(default=1000)),
                ('ranking_absolute', models.PositiveIntegerField(default=0)),
                ('ranking_category', models.PositiveIntegerField(default=0)),
                ('updated_week', models.PositiveIntegerField(default=0)),
                ('updated_season', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_stats', to='rivals.player')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerTotalStats',
        ),
    ]
