# Generated by Django 5.0.1 on 2025-01-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0017_playerseasonstats_matches_rted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
