# Generated by Django 5.0.1 on 2025-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0018_alter_playerseasonstats_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
