# Generated by Django 5.0.1 on 2025-02-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0019_alter_playerseasonstats_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertournament',
            name='games_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertournament',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertournament',
            name='games_rted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertournament',
            name='games_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertournament',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
