# Generated by Django 5.0.1 on 2025-02-11 12:19

import django.db.models.deletion
import rivals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0020_playertournament_games_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=models.SET(rivals.models.get_deleted_player), related_name='pair_p1_set', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=models.SET(rivals.models.get_deleted_player), related_name='pair_p2_set', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_matches', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='playertournament',
            name='player',
            field=models.ForeignKey(on_delete=models.SET(rivals.models.get_deleted_player), related_name='player_tournaments', to='rivals.player'),
        ),
    ]
