# Generated by Django 5.0.1 on 2025-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0021_alter_pair_player1_alter_pair_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('FI', 'Finished'), ('CA', 'Cancelled'), ('OD', 'Overdue')], default='PD', max_length=2),
        ),
    ]
