# Generated by Django 5.0.1 on 2025-02-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0022_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_matches_as_opponent', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_matches_as_player', to='rivals.player'),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
