# Generated by Django 5.0.1 on 2025-02-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0023_alter_playermatch_opponent_alter_playermatch_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='opponent_is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='set1_has_tiebreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='set2_has_tiebreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='set3_has_tiebreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='set3_is_tiebreak',
            field=models.BooleanField(default=False),
        ),
    ]
