# Generated by Django 5.0.1 on 2025-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0024_playermatch_opponent_is_withdrawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
