# Generated by Django 5.0.1 on 2025-02-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0025_player_first_name_player_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tokens', to='rivals.match')),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tokens', to='rivals.player')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_tokens', to='rivals.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
