# Generated by Django 5.0.1 on 2025-02-23 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0026_reviewtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatch',
            name='NTRP_gained',
        ),
        migrations.AddField(
            model_name='playermatch',
            name='NTRP_change',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('M', 'Match'), ('R', 'Review'), ('C', 'Challenge'), ('N', 'New Rating'), ('T', 'Tournament'), ('P', 'Pair'), ('S', 'Success'), ('F', 'Failure'), ('O', 'Other'), ('E', 'Event'), ('I', 'Info'), ('W', 'Warning'), ('D', 'Danger'), ('L', 'Light'), ('H', 'High'), ('M', 'Medium')], max_length=2)),
                ('color', models.CharField(choices=[('G', 'Green'), ('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('P', 'Purple'), ('O', 'Orange'), ('L', 'Light Blue'), ('D', 'Dark Blue'), ('V', 'Violet'), ('W', 'White'), ('G', 'Gray'), ('B', 'Black'), ('T', 'Turquoise'), ('M', 'Magenta'), ('C', 'Cyan'), ('A', 'Aqua')], max_length=2)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('action_text', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('check_field', models.CharField(blank=True, max_length=255, null=True)),
                ('from_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events_from', to='rivals.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='rivals.player')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
