# Generated by Django 5.0.1 on 2025-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0027_remove_playermatch_ntrp_gained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='NTRP_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='season_pts_gained',
            field=models.SmallIntegerField(null=True),
        ),
    ]
