# Generated by Django 5.0.1 on 2025-02-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0028_alter_playermatch_ntrp_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_tournaments', to='rivals.tournament'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='color',
            field=models.CharField(choices=[('1', 'primary'), ('2', 'secondary'), ('I', 'info'), ('W', 'warning'), ('D', 'danger'), ('S', 'success'), ('G', 'green'), ('R', 'red'), ('B', 'blue'), ('Y', 'yellow'), ('P', 'purple'), ('O', 'orange'), ('L', 'light'), ('V', 'violet'), ('G', 'gray'), ('B', 'black'), ('T', 'turquoise'), ('M', 'magenta'), ('C', 'cyan'), ('A', 'aqua')], max_length=2),
        ),
    ]
