# Generated by Django 5.0.1 on 2025-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0029_alter_playertournament_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercurrentstats',
            name='updated_season',
        ),
        migrations.RemoveField(
            model_name='playercurrentstats',
            name='updated_week',
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='geo',
            field=models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('GE', 'Georgia'), ('RU', 'Russia')], default='GE', max_length=2),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='max_season_NTRP',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='min_season_NTRP',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='ranking_absolute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='ranking_category',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='season_final_NTRP',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='season_start_NTRP',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='playercurrentstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
