# Generated by Django 5.0.1 on 2025-02-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0030_remove_playercurrentstats_updated_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='is_approved_by_opponent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='is_approved_by_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='is_implemented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
