# Generated by Django 5.0.1 on 2025-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0031_playermatch_is_approved_by_opponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
