# Generated by Django 5.0.1 on 2025-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0032_alter_pairseasonstats_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstats',
            name='geo',
            field=models.CharField(choices=[('MT', 'Malta'), ('IT', 'Italy'), ('RS', 'Serbia'), ('GE', 'Georgia'), ('RU', 'Russia')], max_length=2),
        ),
    ]
