# Generated by Django 5.0.1 on 2025-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0033_alter_playerseasonstats_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='NTRP_before_match',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
