# Generated by Django 5.0.1 on 2025-03-09 08:33

import django.db.models.deletion
import rivals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0035_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageProlongationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField()),
                ('to_date', models.DateField(default=rivals.models.next_monday)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prolongation_requests_from', to='rivals.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prolongation_requests', to='rivals.tournament')),
            ],
        ),
    ]
