# Generated by Django 5.0.1 on 2025-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0036_stageprolongationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageprolongationrequest',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
