# Generated by Django 5.0.1 on 2025-03-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0037_stageprolongationrequest_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
