# Generated by Django 5.0.1 on 2025-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0038_alter_pairseasonstats_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C2', 'Tour'), ('C3', 'Masters'), ('PR', 'Profi')], default='C0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('C0', 'Novice'), ('C1', 'Challenger'), ('C2', 'Tour'), ('C3', 'Masters'), ('PR', 'Profi')], max_length=2),
        ),
    ]
