# Generated by Django 5.0.1 on 2025-04-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0039_alter_pairseasonstats_week_alter_player_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.CreateModel(
            name='PlayerOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ob_first_name', models.BooleanField(default=False)),
                ('ob_last_name', models.BooleanField(default=False)),
                ('ob_birthdate', models.BooleanField(default=False)),
                ('ob_gender', models.BooleanField(default=False)),
                ('ob_city', models.BooleanField(default=False)),
                ('ob_main_info', models.BooleanField(default=False)),
                ('ob_avatar', models.BooleanField(default=False)),
                ('ob_height', models.BooleanField(default=False)),
                ('ob_weight', models.BooleanField(default=False)),
                ('ob_tennis_exp_years', models.BooleanField(default=False)),
                ('ob_availability', models.BooleanField(default=False)),
                ('ob_additional_info', models.BooleanField(default=False)),
                ('ob_first_tournament_registration', models.BooleanField(default=False)),
                ('ob_first_match_played', models.BooleanField(default=False)),
                ('ob_first_opponent_review', models.BooleanField(default=False)),
                ('ob_wizard_completed', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='rivals.player')),
            ],
        ),
    ]
