# Generated by Django 5.0.1 on 2025-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0040_alter_pairseasonstats_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeronboarding',
            name='ob_verify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playeronboarding',
            name='ob_verify_tg',
            field=models.BooleanField(default=False),
        ),
    ]
