# Generated by Django 5.0.1 on 2025-05-09 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0042_alter_pairseasonstats_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=19),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('season', models.PositiveIntegerField(default=2025)),
                ('week', models.PositiveIntegerField(default=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('award_type', models.CharField(choices=[('SP', 'Season Points'), ('NT', 'NTRP Points')], max_length=2)),
                ('received_via', models.CharField(choices=[('OB', 'Onboarding'), ('MW', 'Match Win'), ('ML', 'Match Loss'), ('MR', 'Match RTed'), ('SP', 'Stage Prolongation'), ('OR', 'Opponent Review'), ('WC', 'Wizard Completion'), ('TR', 'Tournament Result')], max_length=2)),
                ('is_implemented', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='rivals.player')),
            ],
        ),
    ]
