# Generated by Django 5.0.1 on 2025-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0043_alter_pairseasonstats_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='week',
            field=models.PositiveIntegerField(default=41),
        ),
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=41),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=41),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('M', 'Match'), ('R', 'Review'), ('C', 'Challenge'), ('N', 'New Rating'), ('T', 'Tournament'), ('P', 'Pair'), ('S', 'Success'), ('F', 'Failure'), ('O', 'Other'), ('E', 'Event'), ('I', 'Info'), ('W', 'Warning'), ('D', 'Danger'), ('L', 'Light'), ('H', 'High'), ('B', 'Onboarding')], max_length=2),
        ),
    ]
