# Generated by Django 5.0.1 on 2026-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0044_alter_award_week_alter_pairseasonstats_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='season',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='award',
            name='week',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='pairseasonstats',
            name='season',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='season',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
