# Generated by Django 5.0.1 on 2026-04-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0045_alter_award_weekseason_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='week',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
