# Generated by Django 5.0.1 on 2026-04-13 19:45

import rivals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0046_alter_award_week_alter_pairseasonstats_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='week',
            field=models.PositiveIntegerField(default=rivals.models.current_week),
        ),
        migrations.AlterField(
            model_name='pairseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=rivals.models.current_week),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='week',
            field=models.PositiveIntegerField(default=rivals.models.current_week),
        ),
    ]
