# Generated by Django 5.0.1 on 2026-08-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costscenario',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('recommended', 'Recommended'), ('review', 'Review manually'), ('not_recommended', 'Not recommended')], max_length=20),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='recommendation_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes_set', to='buying.costscenario'),
        ),
        migrations.AddField(
            model_name='manualoverride',
            name='kind',
            field=models.CharField(choices=[('component', 'Cost component'), ('final_price', 'Final customer price'), ('offer_field', 'Supplier offer field'), ('removal', 'Override removed')], default='component', max_length=15),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='source',
            field=models.CharField(choices=[('automatic', 'Automatic (matching pipeline)'), ('manual', 'Manual (created by staff)')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='buying.supplieroffer'),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='costscenario',
            name='status',
            field=models.CharField(choices=[('calculated', 'Calculated'), ('calculation_blocked', 'Calculation blocked'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='calculated', max_length=20),
        ),
    ]
