# Generated by Django 5.0.1 on 2026-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0002_costscenario_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costscenario',
            name='break_even_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='declaration_service',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Forwarder declaration service fee (e.g. Onex), applied when import is declared', max_digits=12),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='price_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='price_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='price_standard',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='rule_type',
            field=models.CharField(choices=[('local_tax', 'Local tax'), ('local_shipping', 'Local shipping'), ('international_shipping', 'International shipping'), ('georgia_vat', 'Georgia import VAT'), ('customs', 'Customs declaration fee'), ('declaration_service', 'Declaration service (forwarder)'), ('payment_fee', 'Payment fee'), ('fx_rate', 'FX rate'), ('fx_buffer', 'FX buffer'), ('risk_reserve', 'Risk reserve'), ('sales_vat', 'Sales VAT'), ('small_business_tax', 'Small business tax'), ('margin', 'Margin (selling price markups)'), ('weight', 'Weight'), ('volumetric_weight', 'Volumetric weight'), ('rounding', 'Rounding'), ('handling', 'Handling'), ('insurance', 'Insurance'), ('allocation', 'Allocation')], max_length=30),
        ),
    ]
