# Generated by Django 5.0.1 on 2026-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0003_costscenario_break_even_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('rate_gel', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate_date', models.DateField(db_index=True, help_text='Calendar day the rate is valid for')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('nbg', 'National Bank of Georgia')], default='nbg', max_length=20)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-rate_date', 'currency'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['currency', '-rate_date'], name='buying_fxra_currenc_2e9c32_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('currency', 'rate_date', 'source'), name='buying_fxrate_currency_date_source_uniq'),
        ),
    ]
