# Generated by Django 5.0.1 on 2026-08-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0004_fxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_destination_country',
            field=models.CharField(blank=True, help_text='Default PurchaseContext destination (usually Onex warehouse country)', max_length=2),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_destination_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='onex_applicability',
            field=models.CharField(choices=[('supported', 'Supported'), ('unsupported', 'Unsupported'), ('manual_review', 'Manual review')], default='supported', help_text='Whether an Onex CostScenario may be built for this supplier', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='amount_missing_for_free_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='applied_promotion_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='authenticated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='authentication_status',
            field=models.CharField(blank=True, default='not_applicable', max_length=40),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='destination_selection_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='destination_selection_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='displayed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='effective_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='free_shipping_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='free_shipping_status',
            field=models.CharField(choices=[('free_shipping_reached', 'Free shipping reached'), ('paid_shipping', 'Paid shipping'), ('threshold_unknown', 'Threshold unknown'), ('shipping_calculated_at_checkout', 'Calculated at checkout')], default='threshold_unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='promotions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='public_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='purchase_context_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('purchase_context_unconfirmed', 'Purchase context unconfirmed')], default='confirmed', max_length=40),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='selected_destination_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='selected_destination_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='threshold_basis',
            field=models.CharField(blank=True, default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='unapplied_eligible_promotions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='connector_class',
            field=models.CharField(blank=True, help_text='Registry connector code; empty = manual-only', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 — Onex receiving warehouse country for local delivery', max_length=2),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_display_mode',
            field=models.CharField(choices=[('vat_included', 'VAT included'), ('vat_excluded', 'VAT excluded'), ('sales_tax_at_checkout', 'Sales tax at checkout'), ('destination_based_tax', 'Destination-based tax'), ('no_local_tax', 'No local tax'), ('unknown', 'Unknown'), ('prices_include_vat', 'Prices include VAT (legacy)'), ('tax_at_checkout', 'Tax added at checkout (legacy)'), ('sales_tax_by_state', 'Sales tax by state/address (legacy)')], default='unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='local_shipping_source',
            field=models.CharField(choices=[('parsed', 'Parsed'), ('checkout_simulation', 'Checkout simulation'), ('configured_rule', 'Configured rule'), ('historical_estimate', 'Historical estimate'), ('manual_override', 'Manual override'), ('manual_entry', 'Manual entry'), ('unknown', 'Unknown')], default='configured_rule', max_length=25),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='supplier_tax_source',
            field=models.CharField(choices=[('parsed', 'Parsed'), ('checkout_simulation', 'Checkout simulation'), ('configured_rule', 'Configured rule'), ('historical_estimate', 'Historical estimate'), ('manual_override', 'Manual override'), ('manual_entry', 'Manual entry'), ('unknown', 'Unknown')], default='configured_rule', max_length=25),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='tax_display_mode',
            field=models.CharField(choices=[('vat_included', 'VAT included'), ('vat_excluded', 'VAT excluded'), ('sales_tax_at_checkout', 'Sales tax at checkout'), ('destination_based_tax', 'Destination-based tax'), ('no_local_tax', 'No local tax'), ('unknown', 'Unknown'), ('prices_include_vat', 'Prices include VAT (legacy)'), ('tax_at_checkout', 'Tax added at checkout (legacy)'), ('sales_tax_by_state', 'Sales tax by state/address (legacy)')], default='unknown', max_length=25),
        ),
        migrations.CreateModel(
            name='ConnectorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600)),
                ('fetched_at', models.DateTimeField()),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parser_version', models.CharField(blank=True, max_length=40)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_responses', to='buying.supplier')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='connector_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='buying.connectorresponse'),
        ),
    ]
