# Generated by Django 5.0.1 on 2026-08-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0005_phase3_connectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedproduct',
            name='enrichment_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='normalizedproduct',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='normalizedproduct',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='normalizedproduct',
            name='variant',
            field=models.CharField(blank=True, help_text='Team / Lite / Tour / Plus / Junior / empty for standard', max_length=60),
        ),
        migrations.CreateModel(
            name='RacquetSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('model_family', models.CharField(help_text='e.g. Pure Drive, Blade, EZONE — without head size / weight tokens', max_length=120)),
                ('generation', models.CharField(blank=True, max_length=60)),
                ('variant', models.CharField(blank=True, help_text='Team, Lite, Tour, Plus, Junior, or empty for standard', max_length=60)),
                ('head_size_sqin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_g_unstrung', models.PositiveIntegerField(blank=True, null=True)),
                ('string_pattern', models.CharField(blank=True, max_length=20)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('manufacturer_code', models.CharField(blank=True, max_length=80)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racquet_specs', to='buying.canonicalproduct')),
            ],
            options={
                'ordering': ['brand', 'model_family', 'generation', 'variant', 'head_size_sqin'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['brand', 'model_family', 'generation'], name='buying_racq_brand_5edb8d_idx')],
            },
        ),
    ]
