# Generated by Django 5.0.1 on 2026-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0006_racquet_enrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieroffer',
            name='eligibility_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('manual_review', 'Manual review'), ('unavailable', 'Unavailable'), ('rejected', 'Rejected')], default='manual_review', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='product_identity_confirmed',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='purchase_context_confirmed',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='requested_variant_confirmed',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
