# Generated by Django 5.0.1 on 2026-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0007_phase3_stabilization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmapping',
            name='confirmed_weight_g',
            field=models.PositiveIntegerField(blank=True, help_text='Historically confirmed parcel/shipping weight for the Shipping Weight Engine', null=True),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='weight_g_actual',
            field=models.PositiveIntegerField(blank=True, help_text='Parcel / shipping weight in grams (not product unstrung weight)', null=True),
        ),
    ]
