# Generated by Django 5.0.1 on 2026-08-20 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0008_shipping_weight_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('recommended_partition', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_batches_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_batches', to='buying.supplier')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BuyingBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('title', models.CharField(max_length=240)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(blank=True, choices=[('racquet', 'Racquet'), ('shoes', 'Shoes'), ('string_reel', 'String reel'), ('string_set', 'String set'), ('overgrip', 'Overgrip'), ('balls', 'Balls'), ('apparel', 'Apparel'), ('bag', 'Bag'), ('accessory', 'Accessory')], max_length=20)),
                ('weight_g', models.PositiveIntegerField(blank=True, help_text='Parcel / shipping weight per unit (g). Empty → category weight rule.', null=True)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('sku_hint', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='buying.buyingbatch')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BuyingBatchQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_kind', models.CharField(choices=[('combined_shipment', 'Combined shipment'), ('partition', 'Partition')], default='combined_shipment', max_length=32)),
                ('partition_key', models.CharField(db_index=True, default='all', max_length=120)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('calculation_blocked', 'Calculation blocked'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='calculated', max_length=24)),
                ('item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('international_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declaration_service', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('georgia_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fx_buffer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('risk_reserve', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('handling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shared_cost_total', models.DecimalField(decimal_places=2, default=0, help_text='Sum of costs allocated across lines (excl. direct item cost).', max_digits=12)),
                ('landed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('break_even_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_standard', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chargeable_weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_min_days', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('calculation_version', models.CharField(max_length=40)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('line_results', models.JSONField(blank=True, default=list, help_text='Per-line shares: item_cost, allocated_shared, landed, prices…')),
                ('confidence', models.CharField(choices=[('exact', 'Exact'), ('mostly_exact', 'Mostly exact'), ('estimated', 'Estimated')], default='estimated', max_length=15)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='buying.buyingbatch')),
                ('fulfillment_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_quotes', to='buying.fulfillmentroute')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes_set', to='buying.buyingbatchquote')),
            ],
            options={
                'ordering': ['rank', '-created_at'],
                'default_permissions': (),
            },
        ),
    ]
