# Generated by Django 5.0.1 on 2026-08-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0009_buying_batch_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingbatchline',
            name='weight_g',
            field=models.PositiveIntegerField(blank=True, help_text='Optional per-unit override (g). Empty → category estimate; box is added once per batch.', null=True),
        ),
    ]
